### ISSUE TITLE
EBSCO icons

### ISSUE THREAD

**Issue by jcpember** [carolynponce/Bb-lti-icons#2]
Here are two different icons for EBSC
![ebscohost_logo-50x50](https://user-images.githubusercontent.com/26933248/162271286-e6a67e1c-6780-407a-ada9-edbb7da8136c.jpeg)
![EBSCO3](https://user-images.githubusercontent.com/26933248/162271333-5c93be47-698a-45ff-afbc-3c0d0e5a2559.jpg)
O

**Comment by jcpember** [comment]
I hope that you can grab each one.  If not I will resubmit.

Thanks,

Craig

**Comment by carolynponce** [comment]
Thank you for sharing. I've added them to the folder. 
Carolyn
